<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/06/13 23:28:08
return array (
  'invite_mode' => 
  array (
    'Default' => 1,
  ),
  'enable_mobile' => 
  array (
    'Default' => 1,
  ),
  'enable_pc' => 
  array (
    'Default' => 1,
  ),
  'self_invite_action' => 
  array (
    'Default' => 'opAuthMailAddress/requestRegisterURL',
  ),
  'help_login_error_action' => 
  array (
    'Name' => 'self_invite_action',
    'Caption' => '',
    'FormType' => '',
    'ValueType' => '',
    'IsConfig' => false,
    'IsRequired' => false,
    'Default' => 'opAuthMailAddress/helpLoginError',
  ),
  'is_check_multiple_address' => 
  array (
    'Name' => 'is_check_multiple_address',
    'Caption' => '登录用邮箱地址设定',
    'FormType' => 'radio',
    'ValueType' => 'text',
    'IsConfig' => true,
    'IsRequired' => true,
    'Default' => 0,
    'Choices' => 
    array (
      1 => 'PC邮箱与手机邮箱两方都可接受',
      0 => 'PC邮箱与手机邮箱其中的一方可以接受',
    ),
  ),
);
