<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:22:41
sfConfig::add(array(
  'app_update_span_minute' => 5,
  'app_blog_action_size' => 20,
  'app_blog_component_size' => 10,
));
