<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/06/15 02:43:21
return array (
  'friend' => 
  array (
    'caption' => 
    array (
      'ja_JP' => 'フレンド',
      'en' => 'Friend',
      'zh_CN' => '朋友',
    ),
  ),
  'my_friend' => 
  array (
    'caption' => 
    array (
      'ja_JP' => 'マイフレンド',
      'en' => 'My Friend',
      'zh_CN' => '我的朋友',
    ),
  ),
  'community' => 
  array (
    'caption' => 
    array (
      'ja_JP' => 'コミュニティ',
      'en' => 'Community',
      'zh_CN' => '社区',
    ),
  ),
  'nickname' => 
  array (
    'caption' => 
    array (
      'ja_JP' => 'ニックネーム',
      'en' => 'Nickname',
      'zh_CN' => '昵称',
    ),
  ),
);
