<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/15 02:43:18
sfConfig::add(array(
  'mod_communitytopic_enabled' => true,
  'mod_communitytopic_view_class' => 'sfPHP',
));
