<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:28:08
sfConfig::add(array(
  'mod_opauthmailaddressplugin_enabled' => true,
  'mod_opauthmailaddressplugin_view_class' => 'sfPHP',
));
