<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/06/13 23:25:03
return array (
  'enable_mobile' => 
  array (
    'Default' => 0,
  ),
  'enable_pc' => 
  array (
    'Default' => 0,
  ),
  'admin_invite' => 
  array (
    'Default' => false,
  ),
);
