<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:24:59
sfConfig::add(array(
  'app_update_span_minute' => 5,
  'app_blog_action_size' => 20,
  'app_blog_component_size' => 10,
  'app_diary_is_upload_images' => true,
  'app_diary_max_image_file_num' => 3,
  'app_diary_comment_is_upload_images' => true,
  'app_diary_comment_max_image_file_num' => 3,
  'app_message_is_upload_images' => true,
  'app_message_max_image_file_num' => 3,
  'app_message_pagenate_size' => 20,
));
