<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/06/13 23:25:05
return array (
  0 => 'docomo.ne.jp',
  1 => 'ezweb.ne.jp',
  2 => 'softbank.ne.jp',
  3 => 'd.vodafone.ne.jp',
  4 => 'h.vodafone.ne.jp',
  5 => 't.vodafone.ne.jp',
  6 => 'c.vodafone.ne.jp',
  7 => 'r.vodafone.ne.jp',
  8 => 'k.vodafone.ne.jp',
  9 => 'n.vodafone.ne.jp',
  10 => 'q.vodafone.ne.jp',
  11 => 's.vodafone.ne.jp',
  12 => 'pdx.ne.jp',
  13 => 'di.pdx.ne.jp',
  14 => 'dj.pdx.ne.jp',
  15 => 'dk.pdx.ne.jp',
  16 => 'wm.pdx.ne.jp',
  17 => 'disney.ne.jp',
  18 => 'willcom.com',
);
