<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:37:29
sfConfig::add(array(
  'mod_communitytopic_enabled' => true,
  'mod_communitytopic_view_class' => 'sfOpenPNE',
));
