<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/06/20 17:12:47
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

