<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/13 23:41:52
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'list' => 
  array (
    'is_secure' => false,
  ),
  'search' => 
  array (
    'is_secure' => false,
  ),
  'listmember' => 
  array (
    'is_secure' => false,
  ),
  'show' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
