<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/13 23:25:03
$this->security = array (
  'registerend' => 
  array (
    'is_secure' => 'on',
    'credentials' => 'SNSRegisterFinish',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
