<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/19 07:46:27
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'homeSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'searchSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'homeSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'layoutA' ? false : 'layoutA'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('/opSkinBasicPlugin/css/main.css', '', array ());
}
else if ($templateName.$this->viewName == 'searchSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layoutC' ? false : 'layoutC'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('/opSkinBasicPlugin/css/main.css', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layoutC' ? false : 'layoutC'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('/opSkinBasicPlugin/css/main.css', '', array ());
}

// auto-generated by sfOpenPNEViewConfigHandler
// date: 2011/06/19 07:46:27
if ($templateName.$this->viewName == 'homeSuccess')
{
  $this->setCustomize('communityTopicList', 'communityTopic', 'communityTopicList', array(), array('communityHome',), array('lastRow',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'communityTopicList', 'communityTopic', 'communityTopicList'))));
  $this->setCustomize('communityEventList', 'communityEvent', 'communityEventList', array(), array('communityHome',), array('lastRow',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'communityEventList', 'communityEvent', 'communityEventList'))));
  $this->setCustomize('searchFormLine', 'communityTopic', 'searchFormLine', array(), array('communityHome',), array('after',), false);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'searchFormLine', 'communityTopic', 'searchFormLine'))));
  $this->setCustomize('topSearchForm', 'communityTopic', 'topSearchForm', array(), array('communityImageBox',), array('before',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'topSearchForm', 'communityTopic', 'topSearchForm'))));
}
else if ($templateName.$this->viewName == 'searchSuccess')
{
  $this->setCustomize('topicSearchLink', 'communityTopic', 'topicSearchLink', array(), array('searchCommunity',), array('after',), false);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'topicSearchLink', 'communityTopic', 'topicSearchLink'))));
}
else
{
}

