<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:37:30
sfConfig::add(array(
  'mod_communityevent_enabled' => true,
  'mod_communityevent_view_class' => 'sfOpenPNE',
));
