<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:37:05
sfConfig::add(array(
  'mod_friend_enabled' => true,
  'mod_friend_view_class' => 'sfOpenPNE',
  'mod_friend_default_nav' => 'friend',
));
