<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:37:14
sfConfig::add(array(
  'mod_diarycomment_enabled' => true,
  'mod_diarycomment_view_class' => 'sfOpenPNE',
));
