<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/06/13 23:25:28
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'SNSMember',
  ),
  'registerinput' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'SNSRegisterBegin',
        1 => 'SNSRegisterFinish',
      ),
    ),
  ),
  'configcomplete' => 
  array (
    'is_secure' => false,
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
  'registermobiletoregisterend' => 
  array (
    'credentials' => 'SNSRegisterFinish',
  ),
  'registermobiletoregisterendfinish' => 
  array (
    'is_secure' => false,
  ),
);
