<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/13 23:41:58
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layoutC' ? false : 'layoutC'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('/opSkinBasicPlugin/css/main.css', '', array ());
  $response->addStylesheet('/opDiaryPlugin/css/diary', '', array ());


// auto-generated by sfOpenPNEViewConfigHandler
// date: 2011/06/13 23:41:58



