<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:36:52
sfConfig::add(array(
  'mod_community_enabled' => true,
  'mod_community_view_class' => 'sfOpenPNE',
  'mod_community_default_nav' => 'community',
  'mod_community_nav_list' => 'default',
  'mod_community_nav_joinlist' => 'default',
));
