<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:25:04
sfConfig::add(array(
  'mod_opauthmailaddress_enabled' => true,
  'mod_opauthmailaddress_view_class' => 'sfOpenPNE',
));
