<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/19 07:46:44
sfConfig::add(array(
  'mod_communitytopiccomment_enabled' => true,
  'mod_communitytopiccomment_view_class' => 'sfOpenPNE',
));
