default:
  http_metas:
#    content-type: text/html; charset=Shift_JIS
    content-type: text/html; charset=utf-8
#    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
