<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2011/04/27 09:05:22
return array (
  'enable_mobile' => 
  array (
    'Default' => 0,
  ),
  'enable_pc' => 
  array (
    'Default' => 0,
  ),
  'admin_invite' => 
  array (
    'Default' => false,
  ),
);
