<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/27 09:05:18
sfConfig::add(array(
  'app_update_span_minute' => 5,
  'app_blog_action_size' => 20,
  'app_blog_component_size' => 10,
));
