<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/27 11:29:15
sfConfig::add(array(
  'mod_opauthmailaddress_enabled' => true,
  'mod_opauthmailaddress_view_class' => 'sfPHP',
));
