<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/28 20:43:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=readjapanlocal;host=localhost',
  'username' => 'sunge',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    164 => true,
  ),
  'password' => 'g10p3CAdmin',
  'name' => 'doctrine',
)),);
