<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/13 23:40:00
sfConfig::add(array(
  'app_update_span_minute' => 5,
  'app_blog_action_size' => 20,
  'app_blog_component_size' => 10,
  'app_is_mobile' => true,
  'app_diary_is_upload_images' => false,
  'app_diary_comment_is_upload_images' => false,
  'app_message_is_upload_images' => false,
  'app_message_max_image_file_num' => 3,
  'app_message_pagenatesize' => 10,
));
