<?php
// auto-generated by sfViewConfigHandler
// date: 2011/06/14 00:01:36
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'homeSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'profileSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'homeSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('robots', 'index, follow', false, false);


}
else if ($templateName.$this->viewName == 'profileSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('robots', 'index, follow', false, false);


}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html; charset=utf-8', false);
  $response->addMeta('robots', 'index, follow', false, false);


}

// auto-generated by sfOpenPNEViewConfigHandler
// date: 2011/06/14 00:01:36
if ($templateName.$this->viewName == 'homeSuccess')
{
  $this->setCustomize('cautionAboutFriendPre', 'friend', 'cautionAboutFriendPre', array(), array('information',), array('bottom',), false);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'cautionAboutFriendPre', 'friend', 'cautionAboutFriendPre'))));
  $this->setCustomize('cautionAboutCommunityMemberPre', 'community', 'cautionAboutCommunityMemberPre', array(), array('information',), array('bottom',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'cautionAboutCommunityMemberPre', 'community', 'cautionAboutCommunityMemberPre'))));
  $this->setCustomize('cautionAboutChangeAdminRequest', 'community', 'cautionAboutChangeAdminRequest', array(), array('information',), array('bottom',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'cautionAboutChangeAdminRequest', 'community', 'cautionAboutChangeAdminRequest'))));
  $this->setCustomize('cautionAboutSubAdminRequest', 'community', 'cautionAboutSubAdminRequest', array(), array('information',), array('bottom',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'cautionAboutSubAdminRequest', 'community', 'cautionAboutSubAdminRequest'))));
  $this->setCustomize('noticeUnreadDiaryComment', 'diary', 'noticeUnreadDiaryComment', array(), array('information',), array('bottom',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'noticeUnreadDiaryComment', 'diary', 'noticeUnreadDiaryComment'))));
  $this->setCustomize('unreadMessage', 'message', 'unreadMessage', array(), array('information',), array('bottom',), true);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'unreadMessage', 'message', 'unreadMessage'))));
}
else if ($templateName.$this->viewName == 'profileSuccess')
{
  $this->setCustomize('sendMessageLink', 'message', 'sendMessageLink', array(), array('friendList',), array('before',), false);
  if (sfConfig::get('sf_logging_enabled')) $this->context->getEventDispatcher()->notify(new sfEvent($this, 'application.log', array(sprintf('Set customize "%s" (%s/%s)', 'sendMessageLink', 'message', 'sendMessageLink'))));
}
else
{
}

